/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWargaRouteImport } from './routes/dashboard/warga'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWargaRoute = DashboardWargaRouteImport.update({
  id: '/warga',
  path: '/warga',
  getParentRoute: () => DashboardRoute,
const DashboardCorporateRoute = DashboardCorporateRouteImport.update({
  id: '/dashboard/corporate',
  path: '/dashboard/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTriggerAutomationRoute = ApiTriggerAutomationRouteImport.update({
  id: '/api/trigger-automation',
  path: '/api/trigger-automation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/warga': typeof DashboardWargaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/warga': typeof DashboardWargaRoute
  '/api/trigger-automation': typeof ApiTriggerAutomationRoute
  '/dashboard/corporate': typeof DashboardCorporateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/trigger-automation': typeof ApiTriggerAutomationRoute
  '/dashboard/corporate': typeof DashboardCorporateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/warga': typeof DashboardWargaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/dashboard/warga'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/dashboard/warga'
  id: '__root__' | '/' | '/dashboard' | '/login' | '/dashboard/warga'
  '/api/trigger-automation': typeof ApiTriggerAutomationRoute
  '/dashboard/corporate': typeof DashboardCorporateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/trigger-automation' | '/dashboard/corporate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/trigger-automation' | '/dashboard/corporate'
  id: '__root__' | '/' | '/api/trigger-automation' | '/dashboard/corporate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiTriggerAutomationRoute: typeof ApiTriggerAutomationRoute
  DashboardCorporateRoute: typeof DashboardCorporateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/warga': {
      id: '/dashboard/warga'
      path: '/warga'
      fullPath: '/dashboard/warga'
      preLoaderRoute: typeof DashboardWargaRouteImport
      parentRoute: typeof DashboardRoute
    '/dashboard/corporate': {
      id: '/dashboard/corporate'
      path: '/dashboard/corporate'
      fullPath: '/dashboard/corporate'
      preLoaderRoute: typeof DashboardCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trigger-automation': {
      id: '/api/trigger-automation'
      path: '/api/trigger-automation'
      fullPath: '/api/trigger-automation'
      preLoaderRoute: typeof ApiTriggerAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardWargaRoute: typeof DashboardWargaRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardWargaRoute: DashboardWargaRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiTriggerAutomationRoute: ApiTriggerAutomationRoute,
  DashboardCorporateRoute: DashboardCorporateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
