/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWargaRouteImport } from './routes/dashboard/warga'
import { Route as DashboardCorporateRouteImport } from './routes/dashboard/corporate'
import { Route as ApiRedeemRewardRouteImport } from './routes/api/redeem-reward'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWargaRoute = DashboardWargaRouteImport.update({
  id: '/warga',
  path: '/warga',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCorporateRoute = DashboardCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiRedeemRewardRoute = ApiRedeemRewardRouteImport.update({
  id: '/api/redeem-reward',
  path: '/api/redeem-reward',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/redeem-reward': typeof ApiRedeemRewardRoute
  '/dashboard/corporate': typeof DashboardCorporateRoute
  '/dashboard/warga': typeof DashboardWargaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/redeem-reward': typeof ApiRedeemRewardRoute
  '/dashboard/corporate': typeof DashboardCorporateRoute
  '/dashboard/warga': typeof DashboardWargaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/redeem-reward': typeof ApiRedeemRewardRoute
  '/dashboard/corporate': typeof DashboardCorporateRoute
  '/dashboard/warga': typeof DashboardWargaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/redeem-reward'
    | '/dashboard/corporate'
    | '/dashboard/warga'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/redeem-reward'
    | '/dashboard/corporate'
    | '/dashboard/warga'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/redeem-reward'
    | '/dashboard/corporate'
    | '/dashboard/warga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiRedeemRewardRoute: typeof ApiRedeemRewardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/warga': {
      id: '/dashboard/warga'
      path: '/warga'
      fullPath: '/dashboard/warga'
      preLoaderRoute: typeof DashboardWargaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/corporate': {
      id: '/dashboard/corporate'
      path: '/corporate'
      fullPath: '/dashboard/corporate'
      preLoaderRoute: typeof DashboardCorporateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/redeem-reward': {
      id: '/api/redeem-reward'
      path: '/api/redeem-reward'
      fullPath: '/api/redeem-reward'
      preLoaderRoute: typeof ApiRedeemRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCorporateRoute: typeof DashboardCorporateRoute
  DashboardWargaRoute: typeof DashboardWargaRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCorporateRoute: DashboardCorporateRoute,
  DashboardWargaRoute: DashboardWargaRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiRedeemRewardRoute: ApiRedeemRewardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
